title: Jeff VanSickle Portfolio
description: Projects, code, and other fun stuff
google_analytics: 
show_downloads: true
remote_theme: mmistakes/jekyll-theme-basically-basic

gems:
  - jekyll-mentions
